name: carvel-setup-action
description: Install Carvel apps (ytt, kbld, kapp, kwt, imgpkg and vendir)
author: The Carvel Authors
branding:
  color: 'green'
  icon: 'play'
inputs:
  token:
    description: Github token to use to avoid rate limits
    required: false
    default: ""
  only:
    description: List apps to download if you don't need all
    required: false
    default: ""
  exclude:
    description: List apps to exclude if you want most but not all
    required: false
    default: ""
  ytt:
    description: ytt version
    required: false
    default: latest
  kbld:
    description: kbld version
    required: false
    default: latest
  kapp:
    description: kapp version
    required: false
    default: latest
  kwt:
    description: kwt version
    required: false
    default: latest
  imgpkg:
    description: imgpkg version
    required: false
    default: latest
  vendir:
    description: vendir version
    required: false
    default: latest
  kctrl:
    description: kctrl version
    required: false
    default: latest
runs:
  using: 'node16'
  main: 'dist/index.js'
